2023-03-25 13:12:20,725 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Configure stats pid to 1334
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_131220-fym6yekl/logs/debug.log
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_131220-fym6yekl/logs/debug-internal.log
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_init.py:init():546] calling init triggers
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8009, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 750, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_init.py:init():602] starting backend
2023-03-25 13:12:20,726 INFO    MainThread:1334 [wandb_init.py:init():606] setting up manager
2023-03-25 13:12:20,742 ERROR   MainThread:1334 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 607, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 209, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-03-25 13:12:44,827 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Configure stats pid to 1334
2023-03-25 13:12:44,828 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-25 13:12:44,828 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-25 13:12:44,828 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-25 13:12:44,828 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 13:12:44,828 INFO    MainThread:1334 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_131244-k75oynve/logs/debug.log
2023-03-25 13:12:44,828 INFO    MainThread:1334 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_131244-k75oynve/logs/debug-internal.log
2023-03-25 13:12:44,829 INFO    MainThread:1334 [wandb_init.py:init():546] calling init triggers
2023-03-25 13:12:44,829 INFO    MainThread:1334 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8009, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 750, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-25 13:12:44,829 INFO    MainThread:1334 [wandb_init.py:init():602] starting backend
2023-03-25 13:12:44,829 INFO    MainThread:1334 [wandb_init.py:init():606] setting up manager
2023-03-25 13:12:44,843 ERROR   MainThread:1334 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 607, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 209, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
